export {default as assign} from './assign'
export {default as create} from './create'
export {default as isNativeFunction} from './isNativeFunction'
export {default as typeOf} from './typeOf'
export {default as uuid} from './uuid'